---
title: chem123 exp12 analysis
filters: [../../../heart-hands/06.writing/remove-title-filter.lua]
format: pdf
linestretch: 1.25
fontsize: "11pt"
whitespace: small
geometry:
    - top=1in
    - bottom=1in
    - left=1in
    - right=1in
mainfont: "Times New Roman"
execute:
  echo: false
  output: false
  warning: false
jupyter: python3
bibliography: chem123-exp12-lab-report.bib
csl: ../../../heart-hands/06.writing/citestyles/acs.csl
---

```{python}
import pandas as pd
import matplotlib.pyplot as plt
from dataclasses import dataclass
```

```{python}
# define constants
DROP_VOLUME = (3.6756 / 100) / 1000 # L
STANDARD_SAMPLE_SIZE = 25 / 1000 # L
# useful datatype for handling values alongside their units
@dataclass
class ValueWithUnit:
    value: float
    unit: str

    def fmt(self) -> str:
        '''
        Returns the value as a string, to four sig figs with unit.
        '''
        return '{0:.4f}{1}'.format(self.value, self.unit)
```

\vspace{-12pt}
## Abstract
\vspace{-12pt}
Using titration, the viability of a phosphate buffer as a model for blood's buffering capability was investigated. Through titration, the acid and base buffer capacities of the phosphate buffer were determined. The phosphate buffer was found to have a similar buffer capacity to the blood buffer, making it a useful model.

\vspace{-12pt}
## Introduction
\vspace{-12pt}
The human body maintains blood at a $pH$ range of 7.35-7.45 to properly function and avoid conditions such as acidosis [@nussbaumExperiment12Overview]. To do this, it contains a carbonic acid buffer, shown to have $pH \approx 7.40$ and able to minimize $pH$ change to $-0.167$ when exposed to $20mmol$ of hydrochloric acid [@andersenPHlogPCO2Acidbase1962]. While studying these properties is important for the development of treatments to acidosis, obtaining human blood samples can be difficult, and carbonic acid buffers are unstable at room temperature due to $CO_2$ loss. Thus, other buffers must be used to model blood's buffering behaviour.

In this experiment, it was hypothesized that a phosphate buffer (made from $H_2PO_4^-$ and $HPO_4^{2-}$) with similar $pH$ and acid-base concentrations as blood would have a similar buffer capacity. The buffer capacity of the phosphate buffer was determined through dropwise titration using $0.1M HCl$ and $NaOH$. As the phosphate buffer had similar $pH$ and acid-base concentrations to blood, it was expected to have similar buffer capacities to blood [@andersenPHlogPCO2Acidbase1962].

```{python}
raw_data = pd.read_csv('chem123-exp12-data.csv') \
             .set_index(['Substance'])
```

\vspace{-12pt}
## Experimental
\vspace{-12pt}
A Microlab was connected to a drop counter and $pH$ sensor, and configured to take a $pH$ reading each time a drop was detected. The drop dispenser was calibrated in order to determine the volume of each drop. 100mL of phosphate buffer with $pH = 7.45$ was prepared, using roughly 35.9mL of $0.5M H_2PO_4^-$ and 17.7mL of $1.0M NaOH$.

Then two titrations were performed, each with 25.00mL samples of buffer. The first titration transferred $0.1M HCl$ dropwise until the sample had $pH = 6.45$, the second transferred $0.1 NaOH$ dropwise until the sample had $ph = 8.45$. Titration curves were created using the Microlab, and buffer capacities determined from the drop count. A third titration was performed to simulate the treatment of acidosis. For this, 25.00mL of a "patient trial blood" sample was used, made from phosphate buffer at $pH = 7.029$ to model the blood of a patient undergoing acidosis. $0.2M Na_2HPO_4$ was titrated dropwise into this sample until it was restored to $pH = 7.45$. An additional titration curve was obtained from this titration.

\vspace{-12pt}
## Results
\vspace{-12pt}
```{python}
VOLUME_HCl_ADDED = ValueWithUnit(
    raw_data.loc['HCl', 'Drops'] * DROP_VOLUME,
    'L'
)
ACID_BUFFER_CAPACITY = ValueWithUnit(
    (VOLUME_HCl_ADDED.value * 0.1) / STANDARD_SAMPLE_SIZE,
    'M'
)
VOLUME_NaOH_ADDED = ValueWithUnit(
    raw_data.loc['NaOH', 'Drops'] * DROP_VOLUME,
    'L'
)
BASE_BUFFER_CAPACITY = ValueWithUnit(
    (VOLUME_NaOH_ADDED.value * 0.1) / STANDARD_SAMPLE_SIZE,
    'M'
)
```

```{python}
#| output: true
#| tbl-cap: Vitamin C amounts per microwave exposure time
results = pd.DataFrame({
    'Acid Buffer Capacity': [ACID_BUFFER_CAPACITY.fmt()],
    'Base Buffer Capacity': [BASE_BUFFER_CAPACITY.fmt()],
})
display(results.style.hide_index())
```

The acid buffer capacity of the phosphate buffer was found to be larger than the base buffer capacity.

\vspace{-12pt}
## Discussion
\vspace{-12pt}
The phosphate buffer tested in this experiment was shown to have similar properties to the buffer in blood. As it was made with similar $pH$ and acid-base concentrations as blood, the experimental tests focused on raising and lowering the $pH$ of the phosphate buffer in order to see if it had a similar buffer capacity to blood. The buffer in blood has a significantly higher acid buffer capacity, due to processes in the body creating more acidic byproducts than basic ones [@nussbaumExperiment12Overview]. The phosphate buffer tested in this experiment was found to behave similarly, as its acid buffer capacity was almost 4 times greater than the base buffer capacity. This is in line with results from previous studies, which show that for the same amount of acid and base added to blood, the additional acid creates a lesser change in $pH$ [@andersenPHlogPCO2Acidbase1962].

The phosphate buffer also served as a viable model for modeling different patient blood conditions and possible treatments. The additions of $0.1M HCl$ and $0.1M NaOH$ to samples of the phosphate buffer simulated acidosis and alkalosis respectively. The test with $0.1M HCl$ in particular simulated the effects of gradual blood acidification that would take place in the body as $CO_2$ is produced. The collected titration curves showed the phosphate buffer was able to accurately model the blood buffer's behaviour of minimizing $pH$ changes within a certain range. Similarly, the titration with "patient trial blood" showed that the treatment of acidosis could be properly modeled using the phosphate buffer. The basic component of the buffer was gradually added to the "trial blood" sample, leading to a successful raising of the $pH$, similar to how bicarbonate is administered to treat acidosis in an emergency room setting.

Overall, the results from the experiment supported the hypothesis. The similar buffer capacity and response to additional acid & base exhibited by the phosphate buffer make it a useful model for the buffer in blood. Future improvements to this experiment could repeat the tests conducted multiple times. While the data from each of the tests matched the expected results from previous studies, each test was only conducted once, and as such the accuracy of the data could be improved by collecting more data points. 

\vspace{-12pt}
## Conclusion
\vspace{-12pt}
A phosphate buffer with similar $pH$ and acid-base concentrations as blood was found to be a viable model for the blood buffer, supporting the inital hypothesis. The phosphate buffer exhibited similar buffer capacity and response to additional acid and base when compared to blood.

## Bibliography
::: {#refs}
:::

## Appendix

### Example Calculations

#### [D1] Amount of weak acid required to create phosphate buffer
- $pK_a$ of $H_2PO_4^-$: $-log_{10}(6.3 \cdot 10^{-8}) = 7.2$

\begin{align*}
    pH &= pK_a + \log_{10}\left(\dfrac{[A^-]}{[HA]}\right) \\
    7.45 &= 7.2 + \log_{10}\left(\dfrac{[HPO_4^{2-}]}{[H_2PO_4^-]}\right) \\
    0.25 &= \log_{10}\left(\dfrac{[HPO_4^{2-}]}{[H_2PO_4^-]}\right) \\
    1.77827941 &= \dfrac{[HPO_4^{2-}]}{[H_2PO_4^-]} \\
\end{align*}

then $[HPO_4^{2-}] = 1.778x$ and $[H_2PO_4^-] = x$.

given that the $pH$ drops by 0.2 when $0.020$mol of $H_3O$ are added:

| $HPO_4+$ | $H_3O \rightarrow$ | $H_2PO_4 +$ | $H_2O$ |
|:--------:|:------------------:|:-----------:|:------:|
| $1.778x$         |  0.02      |  $x$        | -      |
| -0.02            | -0.02      | +0.02       | -      |
| $1.778x-0.02$    |  0         |  $x+0.02$   | -      |

\begin{align*}
    pH &= pK_a + \log_{10}\left(\dfrac{[HPO_4^{2-}]}{[H_2PO_4^-]}\right) \\
    7.25 &= 7.2 + \log_{10}\left(\dfrac{1.778x-0.02}{x+0.02}\right) \\
    0.05 &= \log_{10}\left(\dfrac{1.778x-0.02}{x+0.02}\right) \\
    1.122 &= \dfrac{1.778x-0.02}{x+0.02} \\
    0.02244 + 1.122x &= 1.778x-0.02 \\
    0.04244 &= 0.656x \\
    x &= 0.064695122M \\
\end{align*}

so original concentrations are:

- $[HPO_4^{2-}] = 1.778 \cdot 0.064695 = 0.11502771M$
- $[H_2PO_4^-] = 0.064695M$.

number of moles for each, if we make 100mL of solution:

- $[HPO_4^{2-}] = 0.011680571M \cdot 0.1L = 0.011502771mol$
- $[H_2PO_4^-] = 0.064695M \cdot  0.1L = 0.0064695mol$
- Total: $0.017972271$mol.

starting with $0.5M H_2PO_4^-$, we'll need:
\begin{align*}
    \dfrac{0.017972271}{1L} &= \dfrac{0.5}{xL} \\
    x &= 0.035944542L \\
    &= 35.94mL
\end{align*}

#### [D2] Acid buffer capacity
Using the formula:
$$
B = \dfrac{V_a \cdot C}{V_b}
$$
where:

- $V_a$ is the volume of the acid/base added
- $C$ is the concentration of the acid/base added
- $V_b$ is the volume of the buffer

\begin{align*}
    B_{\text{acid}} &= \dfrac{
        (685 \cdot 3.68 \cdot 10^{-5}L ) \cdot 0.1M
    }{0.025L} \\
    &= 0.1007M
\end{align*}

#### [D3] Base buffer capacity
\begin{align*}
    B_{\text{base}} &= \dfrac{
        (176 \cdot 3.68 \cdot 10^{-5}L ) \cdot 0.1M
    }{0.025L} \\
    &= 0.0259M
\end{align*}


#### [D4] Which buffer capacity is higher?
Given that `{python} ACID_BUFFER_CAPACITY.fmt()` > `{python} BASE_BUFFER_CAPACITY.fmt()`, the acid buffer capacity of blood is therefore greater than the base buffer capacity of blood.

#### [D5] Restoration Solution required to reverse acidosis for 25mL sample of "Patient Trial" blood
```{python}
RS_USED = ValueWithUnit(695 * DROP_VOLUME * 1000, 'mL')
```
\begin{align*}
    \text{amount} &= (695 \cdot 3.68 \cdot 10^{-5}L) \\
    &= 0.025576L
    &= 25.576mL
\end{align*}
`{python} RS_USED.fmt()` of restoration solution was used.

#### [D6] Which component of the phosphate buffer comprises the Restoration Solution?
Since the Restoration Solution raises the $pH$, we can assume that it is made out of the basic component of the phosphate buffer, aka $HPO_4^{2-}$.

#### [D7] Amount of Restoration Solution required to restore 7.0L of patient trial blood to $pH = 7.450$

```{python}
EXPERIMENTAL_PH_CHANGE = ValueWithUnit(7.453 - 7.029, '')
REQUIRED_PH_CHANGE = ValueWithUnit(7.450 - 7.029, '')
mL_TO_RAISE_1_UNIT = ValueWithUnit(
    RS_USED.value / EXPERIMENTAL_PH_CHANGE.value,
    'mL'
)
AMOUNT_NEEDED_FOR_25mL = ValueWithUnit(
    mL_TO_RAISE_1_UNIT.value * REQUIRED_PH_CHANGE.value,
    'mL'
)
AMOUNT_NEEDED_FOR_7L = ValueWithUnit(
    AMOUNT_NEEDED_FOR_25mL.value * 40 * 7 / 1000, 'L'
)
AMOUNT_NEEDED_FOR_7L.fmt()
```

From original experiment:

- $pH = 7.029$ for the patient trial blood.
- $7.453 - 7.029 =$ `{python} EXPERIMENTAL_PH_CHANGE.fmt()` pH change when `{python} RS_USED.fmt()` of Restoration Solution added.

We can determine:

- to raise back to $pH = 7.450$: $pH$ needs to be raised by `{python} REQUIRED_PH_CHANGE.fmt()`.
- to raise 25mL of trial blood by 1 pH unit: `{python} RS_USED.fmt()` / `{python} EXPERIMENTAL_PH_CHANGE.fmt()` = `{python} mL_TO_RAISE_1_UNIT.fmt()` of Restoration Solution
- to raise 25mL of trial blood by `{python} REQUIRED_PH_CHANGE.fmt()`: `{python} mL_TO_RAISE_1_UNIT.fmt()` $\cdot$ `{python} REQUIRED_PH_CHANGE.fmt()` = `{python} AMOUNT_NEEDED_FOR_25mL.fmt()`
- to raise 7L of trial blood by `{python} REQUIRED_PH_CHANGE.fmt()`: `{python} AMOUNT_NEEDED_FOR_25mL.fmt()` $\cdot 40 \cdot 7 =$ `{python} AMOUNT_NEEDED_FOR_7L.fmt()`

#### [D8] ER Chart
```{python}
er_chart = pd.DataFrame({
    'pH': [7.00, 7.10, 7.20, 7.30, 7.40]
})
WEIGHTS = [50, 55, 60, 65, 70, 75, 80]
```

Let us use a 50kg patient at $pH = 7.2$ for the example calculation.

First, we can convert the patient weight in kg to blood volume in litres, by multiplying it by 0.1: $50 \cdot 0.1 = 5.00L$.
```{python}
def body_mass_to_blood_volume(
    body_mass: int = '0'
) -> ValueWithUnit:
    return ValueWithUnit(body_mass * 0.1, 'L')
```

We can reuse our previously calculated value for the amount of Restoration Solution required to raise 25mL of blood by 1 pH unit: `{python} mL_TO_RAISE_1_UNIT.fmt()`.

```{python}
def calculate_rs_needed(
    starting_pH: float,
    blood_volume: ValueWithUnit
) -> ValueWithUnit:
    AMOUNT_NEEDED_FOR_25mL = ValueWithUnit(
        mL_TO_RAISE_1_UNIT.value * (7.45 - starting_pH),
        'mL'
    )
    AMOUNT_NEEDED = ValueWithUnit(
        AMOUNT_NEEDED_FOR_25mL.value
        * 40
        * blood_volume.value / 1000, 'L'
    )
    return AMOUNT_NEEDED.fmt()
```

Then the amount needed to raise 25mL of the blood by $7.45 - 7.2 = 0.25$ pH: `{python} mL_TO_RAISE_1_UNIT.fmt()` $\cdot 0.25 =$ `{python} ValueWithUnit(mL_TO_RAISE_1_UNIT.value * 0.25, 'mL').fmt()`.

Multiplying that by 40 to get the amount needed to raise 1L of the blood by our desired amount, and then multiplying by the blood volume to get our final amount: `{python} ValueWithUnit(mL_TO_RAISE_1_UNIT.value * 0.25, 'mL').fmt()` $\cdot 40 \cdot 5L =$ `{python} calculate_rs_needed(7.2, ValueWithUnit(5.00, 'L'))`.

We can repeat this for each patient weight and starting $pH$ to create our chart:
```{python}
#| output: true
for weight in WEIGHTS:
    er_chart[f'{weight} kg'] = er_chart['pH'].map(
        lambda x: calculate_rs_needed(
            x,
            body_mass_to_blood_volume(weight)
        )
    )
display(er_chart.style.hide_index())
```
